// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxmsrydfeqfxqjwdvlwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4bXNyeWRmZXFmeHFqd2R2bHdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1OTg2NTYsImV4cCI6MjA2NTE3NDY1Nn0.zA-KNaxR4oX5GBCTZYuaYJgltjL5ZsRQOFgNW-GcGdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);